name: Build and Push Docker Image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata (slim)
        id: meta-slim
        uses: docker/metadata-action@v5
        with:
          images: |
            name=rommapp/romm
            name=ghcr.io/rommapp/romm
          flavor: |
            latest=auto
            suffix=-slim,onlatest=true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.version={{version}}-slim
            org.opencontainers.image.title="rommapp/romm"
            org.opencontainers.image.description="RomM (ROM Manager) allows you to scan, enrich, and browse your game collection with a clean and responsive interface. With support for multiple platforms, various naming schemes and custom tags, RomM is a must-have for anyone who plays on emulators."
            org.opencontainers.image.licenses="AGPLv3"

      - name: Generate Docker metadata (full)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=rommapp/romm
            name=ghcr.io/rommapp/romm
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.version={{version}}
            org.opencontainers.image.title="rommapp/romm"
            org.opencontainers.image.description="RomM (ROM Manager) allows you to scan, enrich, and browse your game collection with a clean and responsive interface. With support for multiple platforms, various naming schemes and custom tags, RomM is a must-have for anyone who plays on emulators."
            org.opencontainers.image.licenses="AGPLv3"

      - name: Set version
        run: |
          sed -i 's/<version>/${{ steps.meta.outputs.version }}/' backend/__version__.py

      - name: Build slim image
        id: build-slim
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta-slim.outputs.tags }}
          labels: ${{ steps.meta-slim.outputs.labels }}
          target: slim-image

      - name: Build full image
        id: build-full
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: full-image
